"""Tenant stats and logs sub-resource commands."""

from __future__ import annotations

from typing import Annotated, Any

import typer

from verge_cli.columns import TENANT_LOG_COLUMNS, TENANT_STATS_COLUMNS
from verge_cli.context import get_context
from verge_cli.errors import handle_errors
from verge_cli.output import output_result
from verge_cli.utils import resolve_resource_id

# ---------------------------------------------------------------------------
# Two Typer apps: stats + logs
# ---------------------------------------------------------------------------

stats_app = typer.Typer(
    name="stats",
    help=(
        "Read CPU, RAM, and I/O metrics for a tenant.\n\n"
        "**Tenant stats** report the resource footprint of a nested tenant"
        " as seen by the parent system: CPU utilization, RAM consumption"
        " against the tenant's allocation, and disk I/O counts on the"
        " tenant's storage tiers. The `current` command returns the"
        " real-time 5-second heartbeat sample; `history` pulls the"
        " short-term history table, which retains one record per"
        " collection interval (typically 5-minute samples aligned with"
        " 95th-percentile billing conventions). Use these metrics for"
        " live dashboards, recent-incident correlation, and input to"
        " subscription alerts — long-term capacity planning uses the"
        " aggregated long-history tier, which is not exposed here.\n\n"
        "Every command takes the tenant as the first argument (name or"
        " numeric key). Use `-o json` for machine-readable output; useful"
        " `--query` targets on `history` are `timestamp`, `cpu_percent`,"
        " `ram_used_mb`, `ram_total_mb`, `disk_read_ops`, and"
        " `disk_write_ops`. Tenant name lookups that match multiple"
        " tenants exit with code 7 — pass the numeric key to disambiguate.\n\n"
        "---\n\n"
        "**Examples:**\n\n"
        "    # Current 5-second heartbeat for a tenant\n"
        "    vrg tenant stats current acme-corp\n\n"
        "    # JSON for agent consumption\n"
        "    vrg -o json tenant stats current acme-corp\n\n"
        "    # Last 20 short-history samples (default)\n"
        "    vrg tenant stats history acme-corp\n\n"
        "    # Pull the last 200 samples for trend inspection\n"
        "    vrg tenant stats history acme-corp --limit 200\n\n"
        "    # Extract just CPU percentages with --query\n"
        "    vrg -o json tenant stats history acme-corp"
        " --query '[].cpu_percent'\n\n"
        "---\n\n"
        "**Notes:**\n\n"
        "`current` returns a single point-in-time record, so table output"
        " renders as key/value pairs rather than rows. `history` is bounded"
        " by the system's `history_stats_short_expire` retention setting"
        " — samples older than that are aggregated into long-term history"
        " and drop out of this view. RAM figures are reported in MB and"
        " reflect the tenant's allocation, not the parent system's total."
    ),
    no_args_is_help=True,
    rich_markup_mode="markdown",
)

logs_app = typer.Typer(
    name="logs",
    help=(
        "Read activity log entries scoped to a tenant.\n\n"
        "The **tenant log** is the parent system's view of events"
        " generated by or against a specific tenant — lifecycle changes,"
        " resource-limit warnings, failed operations, and anything the"
        " parent recorded about that nested environment. Entries follow"
        " the standard VergeOS event-log structure: a severity level"
        " (`critical`, `error`, `warning`, `message`), a message body,"
        " and a microsecond-precision timestamp. Errors and critical"
        " entries are the usual starting point for incident response;"
        " messages are informational audit trail.\n\n"
        "Every command takes the tenant as the first argument (name or"
        " numeric key). Use `-o json` for machine-readable output; useful"
        " `--query` targets are `timestamp`, `type` (severity level), and"
        " `message`. Tenant name lookups that match multiple tenants exit"
        " with code 7 — pass the numeric key to disambiguate.\n\n"
        "---\n\n"
        "**Examples:**\n\n"
        "    # Last 50 log entries for a tenant (default)\n"
        "    vrg tenant logs list acme-corp\n\n"
        "    # Pull more history\n"
        "    vrg tenant logs list acme-corp --limit 500\n\n"
        "    # Errors and critical entries only\n"
        "    vrg tenant logs list acme-corp --errors-only\n\n"
        "    # JSON for pipeline ingestion\n"
        "    vrg -o json tenant logs list acme-corp --errors-only\n\n"
        "    # Filter to messages containing a substring\n"
        "    vrg -o json tenant logs list acme-corp"
        " | jq '.[] | select(.message | contains(\"quota\"))'\n\n"
        "---\n\n"
        "**Notes:**\n\n"
        "This view shows what the parent system logged about the tenant,"
        " not entries recorded inside the tenant's own nested VergeOS"
        " instance — for that, authenticate against the tenant and use"
        " `vrg log` there. `--errors-only` maps to the parent log's"
        " error/critical filter and is the recommended starting point"
        " during incident investigation."
    ),
    no_args_is_help=True,
    rich_markup_mode="markdown",
)


# ---------------------------------------------------------------------------
# Shared helper
# ---------------------------------------------------------------------------


def _get_tenant(ctx: typer.Context, tenant_identifier: str) -> tuple[Any, Any]:
    """Get the VergeContext and Tenant object."""
    vctx = get_context(ctx)
    key = resolve_resource_id(vctx.client.tenants, tenant_identifier, "Tenant")
    tenant_obj = vctx.client.tenants.get(key)
    return vctx, tenant_obj


# ---------------------------------------------------------------------------
# Converters
# ---------------------------------------------------------------------------


def _stats_current_to_dict(stats: Any) -> dict[str, Any]:
    """Convert a TenantStats object to a dict for output."""
    return {
        "ram_used_mb": stats.ram_used_mb,
        "last_update": stats.last_update,
        "tenant_key": stats.tenant_key,
    }


def _stats_history_to_dict(entry: Any) -> dict[str, Any]:
    """Convert a TenantStatsHistory object to a dict for output."""
    return {
        "timestamp": entry.get("timestamp", ""),
        "cpu_percent": entry.total_cpu,
        "ram_used_mb": entry.ram_used_mb,
        "ram_total_mb": entry.ram_allocated_mb,
        "disk_read_ops": entry.get("disk_read_ops", ""),
        "disk_write_ops": entry.get("disk_write_ops", ""),
    }


def _log_to_dict(entry: Any) -> dict[str, Any]:
    """Convert a TenantLog object to a dict for output."""
    return {
        "timestamp": str(entry.timestamp) if entry.timestamp else "",
        "type": entry.level,
        "message": entry.text,
    }


# ===== Stats Commands =====


@stats_app.command("current")
@handle_errors()
def stats_current(
    ctx: typer.Context,
    tenant: Annotated[str, typer.Argument(help="Tenant name or key")],
) -> None:
    """Show current resource usage for a tenant."""
    vctx, tenant_obj = _get_tenant(ctx, tenant)
    stats = tenant_obj.stats.get()

    # Stats returns a single object — output as key-value table
    output_result(
        _stats_current_to_dict(stats),
        output_format=vctx.output_format,
        query=vctx.query,
        quiet=vctx.quiet,
        no_color=vctx.no_color,
    )


@stats_app.command("history")
@handle_errors()
def stats_history(
    ctx: typer.Context,
    tenant: Annotated[str, typer.Argument(help="Tenant name or key")],
    limit: Annotated[int, typer.Option("--limit", "-l", help="Number of entries")] = 20,
) -> None:
    """Show historical resource usage for a tenant."""
    vctx, tenant_obj = _get_tenant(ctx, tenant)
    history = tenant_obj.stats.history_short(limit=limit)

    output_result(
        [_stats_history_to_dict(e) for e in history],
        output_format=vctx.output_format,
        query=vctx.query,
        columns=TENANT_STATS_COLUMNS,
        quiet=vctx.quiet,
        no_color=vctx.no_color,
    )


# ===== Logs Commands =====


@logs_app.command("list")
@handle_errors()
def logs_list(
    ctx: typer.Context,
    tenant: Annotated[str, typer.Argument(help="Tenant name or key")],
    limit: Annotated[int, typer.Option("--limit", "-l", help="Number of entries")] = 50,
    errors_only: Annotated[
        bool, typer.Option("--errors-only", help="Show only error entries")
    ] = False,
) -> None:
    """List activity log entries for a tenant."""
    vctx, tenant_obj = _get_tenant(ctx, tenant)
    entries = tenant_obj.logs.list(limit=limit, errors_only=errors_only)
    data = [_log_to_dict(e) for e in entries]

    output_result(
        data,
        output_format=vctx.output_format,
        query=vctx.query,
        columns=TENANT_LOG_COLUMNS,
        quiet=vctx.quiet,
        no_color=vctx.no_color,
    )
